-- Manual Next Actions (CRM v1.1.0 Phase 1). Extends, not replaces, the
-- existing automatic stage-based Next Action (lib/nextAction.ts,
-- leads.next_action_date). A lead may have zero or more open rows here;
-- the CRM picks the single highest-priority open item (automatic or
-- manual) to display — see lib/nextActions.ts.
--
-- completed_at, not just a boolean, so a completed action's timestamp is
-- preserved for future history/reporting — same convention already used
-- for first_text_sent_at / deleted_at elsewhere on leads.
--
-- on delete cascade: an action with no lead to belong to is meaningless.

create table if not exists public.lead_next_actions (
  id bigint generated by default as identity primary key,
  lead_id bigint not null references public.leads(id) on delete cascade,
  title text not null,
  due_at timestamptz not null,
  priority text not null default 'medium' check (priority in ('low', 'medium', 'high')),
  completed boolean not null default false,
  completed_at timestamptz,
  notes text,
  created_at timestamptz not null default now()
);

create index if not exists lead_next_actions_lead_id_idx
  on public.lead_next_actions (lead_id);

-- Partial index — only open actions are ever queried for the unified queue.
create index if not exists lead_next_actions_open_due_idx
  on public.lead_next_actions (due_at)
  where completed = false;

alter table public.lead_next_actions enable row level security;

-- Matches the access pattern every other CRM-only write already relies on
-- (authenticated session via the CRM's Supabase Auth login) — no anon
-- access, same posture as `leads` itself.
create policy "Authenticated users can manage lead_next_actions"
  on public.lead_next_actions
  for all
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');
