-- Foundation for the future workflow engine (CRM v1.1.0, workflow phase).
-- NOT wired into any UI yet — this table exists so the data model is
-- ready, per the "prepare the architecture without changing user
-- behavior" brief. The current follow-up engine (lead_next_actions,
-- lib/nextAction.ts, lib/nextActions.ts) is untouched and keeps driving
-- the Follow-Ups sidebar and Lead Panel exactly as it does today.
--
-- Deliberately distinct from lead_next_actions (which allows zero-or-more
-- manual actions per lead, ranked against the automatic one): this table
-- is a single canonical "where is this lead in the workflow" pointer —
-- enforced via the unique constraint on lead_id, one row per lead, ever,
-- updated in place as the (future) workflow advances. Never insert a
-- second row for the same lead.
--
-- action_type is free text, not a constrained enum — the actual set of
-- workflow steps (Send Apartment List, Schedule Tour, etc.) hasn't been
-- finalized, and baking a fixed list into a CHECK constraint now is
-- exactly the kind of hard-coded assumption this phase is meant to avoid.
-- Validate the allowed set at the application layer once the real engine
-- is built.
--
-- status is the one enum genuinely specified by this phase: due,
-- scheduled, and waiting are all "not actionable right now" in different
-- ways (waiting = waiting on the client; scheduled = waiting on a future
-- date); only "due" (with a due_date of today or earlier) should ever
-- surface in a work queue. See lib/primaryAction.ts for the (currently
-- unused) helper that will apply this rule once wired in.
--
-- completed is a separate boolean, not just inferred from status —
-- matches the field list from spec exactly, and keeps a fast index-able
-- flag distinct from the richer pre-completion status lifecycle.
--
-- Purely additive: nullable dates, no default backfill, no change to any
-- existing row or table.

create table if not exists public.lead_primary_action (
  id bigint generated by default as identity primary key,
  lead_id bigint not null unique references public.leads(id) on delete cascade,
  action_type text not null,
  status text not null default 'due' check (status in ('due', 'scheduled', 'waiting', 'completed')),
  activation_date timestamptz,
  due_date timestamptz,
  completed boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Supports the future "which leads are due today / overdue" query without
-- scanning the whole table — mirrors the partial-index pattern already
-- used for lead_next_actions.
create index if not exists lead_primary_action_due_idx
  on public.lead_primary_action (due_date)
  where status = 'due' and completed = false;

alter table public.lead_primary_action enable row level security;

-- Same access pattern as every other CRM-only table: authenticated
-- session only, no anon access.
create policy "Authenticated users can manage lead_primary_action"
  on public.lead_primary_action
  for all
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');
