-- AI Client Brief table
-- One row per lead. Populated by the iMessage sync + AI summarization pipeline.
-- Phase 1: schema only. Sync and AI generation are wired in Phase 2+.

create table if not exists ai_client_briefs (
  id                  uuid primary key default gen_random_uuid(),

  lead_id             bigint not null references leads(id) on delete cascade,
  constraint ai_client_briefs_lead_id_unique unique (lead_id),

  -- Structured preference data extracted from conversation
  looking_for         jsonb not null default '[]',
  preferences         jsonb not null default '[]',
  deal_breakers       jsonb not null default '[]',

  -- Property feedback
  properties_liked    jsonb not null default '[]',
  properties_disliked jsonb not null default '[]',

  -- Application pipeline
  approval_notes      jsonb not null default '[]',
  client_objections   jsonb not null default '[]',

  -- Free-text fields generated by AI
  current_situation   text,
  last_conversation   text,
  next_action         text,
  ai_summary          text,

  -- Sync tracking — used by Phase 4 incremental updates
  message_count       integer not null default 0,
  last_message_rowid  bigint,
  last_message_date   timestamp with time zone,
  last_synced_at      timestamp with time zone,

  created_at          timestamp with time zone not null default now(),
  updated_at          timestamp with time zone not null default now()
);

-- Keep updated_at current automatically
create or replace function set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger ai_client_briefs_updated_at
  before update on ai_client_briefs
  for each row execute procedure set_updated_at();

-- Index for the foreign key (Postgres doesn't create one automatically for unique constraints)
create index if not exists ai_client_briefs_lead_id_idx on ai_client_briefs(lead_id);
