-- Favorites Phase 1 (manual only — see components/crm/FavoriteModal.tsx and
-- the "⭐ Favorites" section in LeadPanel.tsx). Not yet integrated with the
-- Property Matches database, no URL scraping, no auto-population — a
-- client's favorite communities are entered by hand for now. Later phases
-- will wire this into Text Top 3, Ready to Tour, and tour planning.

create table if not exists public.lead_favorites (
  id bigint generated by default as identity primary key,
  lead_id bigint not null references public.leads(id) on delete cascade,
  property_name text not null,
  property_url text not null,
  property_address text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists lead_favorites_lead_id_idx on public.lead_favorites (lead_id);

alter table public.lead_favorites enable row level security;

create policy "Authenticated users can manage lead_favorites"
  on public.lead_favorites
  for all
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');
