-- ============================================================================
-- Locator Beast — core CRM tables (intentional baseline)
-- ============================================================================
-- Hand-authored, NOT dumped. `leads` and `lead_properties` previously existed
-- only in the Lone Star database (untracked schema drift). They are recreated
-- here as clean, intentional Locator Beast migrations so the whole schema is
-- reproducible from this repo alone: a new dev can create an empty Supabase
-- project, run the migrations in order, and get the complete database WITHOUT
-- any access to the Lone Star project.
--
-- This baseline is dated first (before every existing migration) and defines
-- the ORIGINAL columns. Later feature migrations (marketing attribution, archive
-- reason, closed_at, soft-delete, invoice/commission, workspace ownership, etc.)
-- add the rest in order — the intentional incremental history is preserved.
--
-- Column set = what the current CRM app actually uses, verified against the live
-- schema as a read-only reference. Intentionally EXCLUDED (zero app references —
-- Lone Star SMS-automation drift): last_sms_at, welcome_sms_sent_at,
-- email_opt_in, internal_notes. The remaining sms_* columns are kept only
-- because the app still references them; they are Lone Star SMS-automation
-- legacy and are candidates for a future intentional cleanup once fully audited.

-- ── leads ────────────────────────────────────────────────────────────────────
create table if not exists public.leads (
  id                     bigint generated by default as identity primary key,
  created_at             timestamptz not null default now(),
  lead_type              text not null default 'renter',

  -- Contact / identity
  first_name             text,
  last_name              text,
  phone                  text,
  email                  text,

  -- Search criteria
  move_date              date,
  city                   text,
  neighborhoods          text,
  submarkets             text,
  property_type          text,
  desired_rent           text,
  beds                   text,
  baths                  text,
  income                 text,
  website                text,
  lead_category          text,

  -- Screening
  credit_history         text,
  credit_score           text,
  broken_lease_age       text,
  broken_lease_amount    text,
  eviction_court         text,
  eviction_age           text,
  eviction_balance       text,
  felony_age             text,
  misdemeanor_age        text,
  criminal_background    text,
  criminal_charge        text,

  -- Notes
  notes                  text,
  locator_notes          text,

  -- Consent + Lone Star SMS-automation legacy (kept: still app-referenced)
  sms_opt_in             boolean not null default false,
  sms_consent_at         timestamptz,
  sms_welcome_sent       boolean not null default false,
  sms_welcome_sent_at    timestamptz,
  sms_followup_3d_sent   boolean not null default false,
  sms_followup_3d_sent_at timestamptz,
  has_replied            boolean not null default false,
  day3_sent_at           timestamptz,
  sms_replied            boolean,
  sms_replied_at         timestamptz,

  -- Social handles
  instagram              text,
  tiktok                 text,
  facebook               text,

  -- CRM workflow (the pipeline the Kanban/Lead Panel drive)
  source                 text,
  crm_status             text default 'new',
  priority               text,
  follow_up_count        integer default 0,
  last_contacted_at      timestamptz,
  next_follow_up         date,
  next_action_date       timestamp,          -- matches live (tz-naive); do not "fix" without a data pass
  google_contact_id      text
);

create index if not exists leads_crm_status_idx on public.leads (crm_status);
create index if not exists leads_created_at_idx on public.leads (created_at desc);
create index if not exists leads_phone_idx      on public.leads (phone);

-- Closed by default; the workspace-scoped policy is added by the workspace
-- foundation (20260728000008). Service-role migrations/inserts bypass RLS.
alter table public.leads enable row level security;

-- ── lead_properties ──────────────────────────────────────────────────────────
-- LeadInsights "favorite an AI-matched property" toggles. Intentionally
-- DECOUPLED from the Lone Star `properties` content table (excluded from Locator
-- Beast): property_id is a plain identifier, not a FK to a Lone Star table.
create table if not exists public.lead_properties (
  id           uuid primary key default gen_random_uuid(),
  lead_id      bigint not null references public.leads(id) on delete cascade,
  property_id  uuid not null,
  status       text not null default 'favorite',
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);
create index if not exists lead_properties_lead_idx on public.lead_properties (lead_id);

alter table public.lead_properties enable row level security;
